// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/kube-incubator/tomcat-operator/pkg/apis/tomcat/v1alpha1.Tomcat":       schema_pkg_apis_tomcat_v1alpha1_Tomcat(ref),
		"github.com/kube-incubator/tomcat-operator/pkg/apis/tomcat/v1alpha1.TomcatSpec":   schema_pkg_apis_tomcat_v1alpha1_TomcatSpec(ref),
		"github.com/kube-incubator/tomcat-operator/pkg/apis/tomcat/v1alpha1.TomcatStatus": schema_pkg_apis_tomcat_v1alpha1_TomcatStatus(ref),
	}
}

func schema_pkg_apis_tomcat_v1alpha1_Tomcat(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Tomcat is the Schema for the tomcats API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/kube-incubator/tomcat-operator/pkg/apis/tomcat/v1alpha1.TomcatSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/kube-incubator/tomcat-operator/pkg/apis/tomcat/v1alpha1.TomcatStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/kube-incubator/tomcat-operator/pkg/apis/tomcat/v1alpha1.TomcatSpec", "github.com/kube-incubator/tomcat-operator/pkg/apis/tomcat/v1alpha1.TomcatStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_tomcat_v1alpha1_TomcatSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "TomcatSpec defines the desired state of Tomcat",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_tomcat_v1alpha1_TomcatStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "TomcatStatus defines the observed state of Tomcat",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
